standalone: 
	g++ -Wall -g -fpermissive FullTest.cpp -lm -I../stk/ -o FullTest.out
	./FullTest.out

fast:
	g++ -Wall -g -fpermissive FullTest.cpp -lm -I../stk/ -o FullTest.out
	./FullTest.out fast
	
clean:
	rm -rf *.so *.out *.wav /gen/*.txt
